In [1]:
import pandas as pd


df_initial=pd.read_csv("./initial_instruction_evaluations.csv",index_col=False)
df_best=pd.read_csv("./GPT-4_best_instruction_evaluations.csv",index_col=False)
for i in range(20):
    print(str(df_initial["human 1 eval"][i])+"& "+str(df_initial["human 2 eval"][i])+" & "+str(df_initial["human 3 eval"][i])+"&"+str(int(df_initial["eval"][i]))+"\\\\")
    

6& 6 & 7&8\\
1& 2 & 2&1\\
7& 5 & 6&8\\
7& 4 & 5&3\\
7& 5 & 5&7\\
6& 6 & 6&6\\
6& 5 & 6&7\\
6& 6 & 6&6\\
4& 4 & 5&6\\
6& 7 & 7&8\\
5& 5 & 6&7\\
4& 6 & 6&7\\
5& 6 & 5&8\\
6& 8 & 7&8\\
5& 7 & 6&7\\
6& 7 & 6&7\\
2& 6 & 4&6\\
4& 2 & 2&2\\
5& 6 & 5&6\\
5& 6 & 7&8\\


In [11]:

df_initial["human 3 eval"]=hum_3_in
df_best["human 3 eval"]=hum_3_fi

df_initial.to_csv("./initial_instruction_evaluations.csv",index=False)
df_best.to_csv("./GPT-4_best_instruction_evaluations.csv",index=False)

In [16]:
import numpy as np

print(np.std(df_initial["eval"]))
print(np.std(df_initial["human 1 eval"]))
print(np.std(df_initial["human 2 eval"]))
print(np.std(df_initial["human 3 eval"]))
print(np.std(df_best["eval"]))
print(np.std(df_best["human 1 eval"]))
print(np.std(df_best["human 2 eval"]))
print(np.std(df_best["human 3 eval"]))

1.977371993328519
1.5256146302392357
1.499166435056495
1.3955285736952863
1.397318861248212
1.2806248474865698
1.9306734576307825
6.1


In [10]:
from sklearn.metrics import cohen_kappa_score
import numpy as np


annotator_scores = [
    df_initial["eval"],
    df_initial["human 1 eval"],
    df_initial["human 2 eval"],
    hum_3_in
]
kappa_matrix = np.zeros((4, 4))

for i in range(4):
    for j in range(i + 1, 4):
        kappa = cohen_kappa_score([annotator_scores[i][q] for q in range(20)],
                                  [annotator_scores[j][q] for q in range(20)])
        kappa_matrix[i][j] = kappa
        kappa_matrix[j][i] = kappa
print("Cohen's Kappa Matrix (initial instruction):")
print(kappa_matrix)
average_kappa = np.mean(kappa_matrix)
print(f"Average Cohen's Kappa (initial instruction): {average_kappa}")


annotator_scores = [
    df_best["eval"],
    df_best["human 1 eval"],
    df_best["human 2 eval"],
    hum_3_fi
]
kappa_matrix = np.zeros((4, 4))

for i in range(4):
    for j in range(i + 1, 4):
        kappa = cohen_kappa_score([int(annotator_scores[i][q]) for q in range(20)],
                                  [int(annotator_scores[j][q]) for q in range(20)])
        kappa_matrix[i][j] = kappa
        kappa_matrix[j][i] = kappa
print("\n\nCohen's Kappa Matrix (GPT4 instruction):")
print(kappa_matrix)
average_kappa = np.mean(kappa_matrix)
print(f"Average Cohen's Kappa (GPT4 instruction): {average_kappa}")

Cohen's Kappa Matrix (initial instruction):
[[ 0.          0.07246377  0.28143713 -0.01796407]
 [ 0.07246377  0.          0.0228013   0.07284768]
 [ 0.28143713  0.0228013   0.          0.12751678]
 [-0.01796407  0.07284768  0.12751678  0.        ]]
Average Cohen's Kappa (initial instruction): 0.06988782319780609


Cohen's Kappa Matrix (GPT4 instruction):
[[ 0.          0.02061856  0.07692308  0.11111111]
 [ 0.02061856  0.          0.01162791 -0.04938272]
 [ 0.07692308  0.01162791  0.          0.08256881]
 [ 0.11111111 -0.04938272  0.08256881  0.        ]]
Average Cohen's Kappa (GPT4 instruction): 0.031683342875253734
